config {
    type: "table",
    schema: "dynamic_events_ip",
    name: "dynamic_events_ip",
    description: "",
    bigquery: {
        clusterBy: ["event_id", "match_id", "team_id", "player_id"]
    },
    uniqueKey:["event_id", "match_id", "team_id", "player_id"],
    assertions:{
        uniqueKey: ["event_id", "match_id", "team_id", "player_id"],
        nonNull: ["event_id", "match_id", "team_id", "player_id"]
    }
}

SELECT
  dynamic_events.*,    
  filtered_options.event_id AS associated_passing_option,
  -- If there is a safe simple options during the possession sequence.
    CASE 
    WHEN dynamic_events.event_type = 'player_possession' AND 
         EXISTS (
           SELECT 1 
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS option_events
           WHERE option_events.event_type != 'player_possession' 
             AND option_events.associated_player_possession_event_id = dynamic_events.event_id
             AND option_events.match_id = dynamic_events.match_id
             AND option_events.xpass_completion >= 0.9
             AND option_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND option_events.interplayer_distance_range != 'long'
         ) THEN TRUE
    WHEN dynamic_events.event_type != 'player_possession' AND 
         EXISTS (
           SELECT 1 
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS option_events
           WHERE option_events.event_type != 'player_possession' 
             AND option_events.associated_player_possession_event_id = dynamic_events.associated_player_possession_event_id
             AND option_events.match_id = dynamic_events.match_id
             AND option_events.xpass_completion >= 0.9
             AND option_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND option_events.interplayer_distance_range != 'long'
         ) THEN TRUE
    ELSE FALSE
  END AS safe_simple_option_avaiable_in_possession, 

  -- If the player in possession targrted a safe simple option.
  CASE 
    WHEN dynamic_events.event_type = 'player_possession' AND 
         EXISTS (
           SELECT 1 
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS passing_events
           WHERE passing_events.event_type = 'passing_option' 
             AND passing_events.associated_player_possession_event_id = dynamic_events.event_id
             AND passing_events.match_id = dynamic_events.match_id
             AND passing_events.xpass_completion >= 0.9
             AND passing_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND passing_events.interplayer_distance_range != 'long'
             AND passing_events.targeted IS TRUE
         ) THEN TRUE
    WHEN dynamic_events.event_type != 'player_possession' THEN NULL 
    ELSE FALSE
  END AS targeted_safe_simple_option, 

  -- Higher level positional group.
  CASE 
    WHEN dynamic_events.player_position IN ('GK') THEN 'Goalkeeper'
    WHEN dynamic_events.player_position IN ('LCB', 'CB', 'RCB') THEN 'Central Defender'
    WHEN dynamic_events.player_position IN ('LWB', 'LB') THEN 'Left Full Back'
    WHEN dynamic_events.player_position IN ('RWB', 'RB') THEN 'Right Full Back'
    WHEN dynamic_events.player_position IN ('LDM', 'DM', 'RDM') THEN 'Defensive Midfield'
    WHEN dynamic_events.player_position IN ('LM', 'AM', 'RM') THEN 'Midfield'
    WHEN dynamic_events.player_position IN ('LW', 'LF') THEN 'Left Wide Attacker'
    WHEN dynamic_events.player_position IN ('RW', 'RF') THEN 'Right Wide Attacker'
    WHEN dynamic_events.player_position IN ('CF') THEN 'Center Forward'
    ELSE 'Other Position'
  END AS player_position_group,

  -- Higher level positional group (player in possession).
  CASE 
    WHEN dynamic_events.player_in_possession_position IN ('GK') THEN 'Goalkeeper'
    WHEN dynamic_events.player_in_possession_position IN ('LCB', 'CB', 'RCB') THEN 'Central Defender'
    WHEN dynamic_events.player_in_possession_position IN ('LWB', 'LB') THEN 'Left Full Back'
    WHEN dynamic_events.player_in_possession_position IN ('RWB', 'RB') THEN 'Right Full Back'
    WHEN dynamic_events.player_in_possession_position IN ('LDM', 'DM', 'RDM') THEN 'Defensive Midfield'
    WHEN dynamic_events.player_in_possession_position IN ('LM', 'AM', 'RM') THEN 'Midfield'
    WHEN dynamic_events.player_in_possession_position IN ('LW', 'LF') THEN 'Left Wide Attacker'
    WHEN dynamic_events.player_in_possession_position IN ('RW', 'RF') THEN 'Right Wide Attacker'
    WHEN dynamic_events.player_in_possession_position IN ('CF') THEN 'Center Forward'
    ELSE 'Other Position'
  END AS player_in_possession_position_group,

  -- Addtional match information.
  match_meta.competition_edition_id,
  match_meta.competition_edition_name,
  match_meta.competition_id,
  match_meta.competition_name,
  match_meta.season_id,
  match_meta.season_name,
  CONCAT(match_meta.home_team_name, ' v ',match_meta.away_team_name,' (', match_meta.date_time, ')') AS match_name,

  CASE WHEN dynamic_events.team_id = match_meta.home_team_id THEN match_meta.away_team_id ELSE match_meta.home_team_id END AS opposition_team_id

FROM     
  ${ref("dynamic_events")} AS dynamic_events 
JOIN 
  ${ref("match_metadata")} AS match_meta
ON dynamic_events.match_id = match_meta.match_id
LEFT JOIN 
  ${ref("dynamic_events")} AS filtered_options
ON 
  dynamic_events.match_id = filtered_options.match_id
  AND dynamic_events.player_id = filtered_options.player_id
  AND dynamic_events.event_type = 'player_possession'
  AND dynamic_events.start_type = 'pass_reception'
  AND filtered_options.event_type = 'passing_option'
  AND filtered_options.targeted = TRUE
  AND dynamic_events.pass_distance_received = filtered_options.pass_distance
  AND dynamic_events.pass_angle_received = filtered_options.pass_angle
  AND dynamic_events.frame_start > filtered_options.frame_start
  AND dynamic_events.frame_start - filtered_options.frame_end <= 60