config {
    type: "table",
    schema: "dynamic_events_ip",
    name: "in_possesion_event",
    description: "Dynamic events filtered on in possession events",
    bigquery: {
        clusterBy: ["event_id", "match_id", "team_id", "player_id"]
    },
    assertions:{
        nonNull: ["event_id", "match_id", "team_id", "player_id"]
    }
}

SELECT
  dynamic_events.*,

  CASE
    WHEN dynamic_events.event_type = 'player_possession' AND
         EXISTS (
           SELECT 1
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS option_events
           WHERE option_events.event_type != 'player_possession'
             AND option_events.associated_player_possession_event_id = dynamic_events.event_id
             AND option_events.match_id = dynamic_events.match_id
             AND option_events.xpass_completion >= 0.9
             AND option_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND option_events.interplayer_distance_range != 'long'
         ) THEN TRUE
    WHEN dynamic_events.event_type != 'player_possession' AND
         EXISTS (
           SELECT 1
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS option_events
           WHERE option_events.event_type != 'player_possession'
             AND option_events.associated_player_possession_event_id = dynamic_events.associated_player_possession_event_id
             AND option_events.match_id = dynamic_events.match_id
             AND option_events.xpass_completion >= 0.9
             AND option_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND option_events.interplayer_distance_range != 'long'
         ) THEN TRUE
    ELSE FALSE
  END AS safe_simple_option_avaiable_in_possession,

  CASE
    WHEN dynamic_events.event_type = 'player_possession' AND
         EXISTS (
           SELECT 1
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS passing_events
           WHERE passing_events.event_type = 'passing_option'
             AND passing_events.associated_player_possession_event_id = dynamic_events.event_id
             AND passing_events.match_id = dynamic_events.match_id
             AND passing_events.xpass_completion >= 0.9
             AND passing_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND passing_events.interplayer_distance_range != 'long'
             AND passing_events.targeted IS TRUE
         ) THEN TRUE
    WHEN dynamic_events.event_type != 'player_possession' THEN NULL
    ELSE FALSE
  END AS targeted_safe_simple_option

FROM
  ${ref("dynamic_events_sandbox", "dynamic_events")} AS dynamic_events

WHERE event_type = 'player_possession'
