config {
    type: "table",
    schema: "dynamic_events_oop",
    name: "dynamic_events_oop",
    description: "Dynamic events filtered on out possession events",
    bigquery: {
        clusterBy: ["event_id", "match_id", "team_id", "player_id"]
    },
    uniqueKey:["event_id", "match_id", "team_id", "player_id"],
    assertions:{
        uniqueKey: ["event_id", "match_id", "team_id", "player_id"],
        nonNull: ["event_id", "match_id", "team_id", "player_id"]
    }
}

SELECT
  dynamic_events.*

FROM
  ${ref("dynamic_events")} AS dynamic_events

WHERE event_type = 'on_ball_engagement'