config {
    type: "table",
    schema: "dynamic_events_oop",
    name: "on_ball_engagement_event",
    description: "Dynamic events filtered on out possession events",
    bigquery: {
        clusterBy: ["event_id", "match_id", "team_id", "player_id"]
    },
    assertions:{
        nonNull: ["event_id", "match_id", "team_id", "player_id"]
    }
}

SELECT
  de.*, mm.competition_edition_id
FROM
  ${ref("events", "dynamic_events")} AS de

JOIN (
  SELECT match_id, MIN(competition_edition_id) AS competition_edition_id
  FROM ${ref("metadata", "match_metadata")}
  GROUP BY match_id
) AS mm
  ON mm.match_id = de.match_id

WHERE de.event_type = 'on_ball_engagement'