config {
    type: "table",
    schema: "dynamic_events_ip",
    name: "dynamic_events_ip",
    description: "",
    bigquery: {
        clusterBy: ["event_id", "match_id", "team_id", "player_id"]
    },
    uniqueKey:["event_id", "match_id", "team_id", "player_id"],
    assertions:{
        uniqueKey: ["event_id", "match_id", "team_id", "player_id"],
        nonNull: ["event_id", "match_id", "team_id", "player_id"]
    }
}

SELECT
  dynamic_events.*,
  filtered_options.event_id AS associated_passing_option,

  CASE
    WHEN dynamic_events.event_type = 'player_possession' AND
         EXISTS (
           SELECT 1
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS option_events
           WHERE option_events.event_type != 'player_possession'
             AND option_events.associated_player_possession_event_id = dynamic_events.event_id
             AND option_events.match_id = dynamic_events.match_id
             AND option_events.xpass_completion >= 0.9
             AND option_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND option_events.interplayer_distance_range != 'long'
         ) THEN TRUE
    WHEN dynamic_events.event_type != 'player_possession' AND
         EXISTS (
           SELECT 1
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS option_events
           WHERE option_events.event_type != 'player_possession'
             AND option_events.associated_player_possession_event_id = dynamic_events.associated_player_possession_event_id
             AND option_events.match_id = dynamic_events.match_id
             AND option_events.xpass_completion >= 0.9
             AND option_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND option_events.interplayer_distance_range != 'long'
         ) THEN TRUE
    ELSE FALSE
  END AS safe_simple_option_avaiable_in_possession,

  CASE
    WHEN dynamic_events.event_type = 'player_possession' AND
         EXISTS (
           SELECT 1
           FROM analysisteam-cloudsql.skillcorner_external_data.dynamic_events AS passing_events
           WHERE passing_events.event_type = 'passing_option'
             AND passing_events.associated_player_possession_event_id = dynamic_events.event_id
             AND passing_events.match_id = dynamic_events.match_id
             AND passing_events.xpass_completion >= 0.9
             AND passing_events.interplayer_direction IN ('sideway_right', 'sideway_left', 'backward')
             AND passing_events.interplayer_distance_range != 'long'
             AND passing_events.targeted IS TRUE
         ) THEN TRUE
    WHEN dynamic_events.event_type != 'player_possession' THEN NULL
    ELSE FALSE
  END AS targeted_safe_simple_option

FROM
  ${ref("dynamic_events")} AS dynamic_events
LEFT JOIN
  ${ref("dynamic_events")} AS filtered_options
ON
  dynamic_events.match_id = filtered_options.match_id
  AND dynamic_events.player_id = filtered_options.player_id
  AND dynamic_events.event_type = 'player_possession'
  AND dynamic_events.start_type = 'pass_reception'
  AND filtered_options.event_type = 'passing_option'
  AND filtered_options.targeted = TRUE
  AND dynamic_events.pass_distance_received = filtered_options.pass_distance
  AND dynamic_events.pass_angle_received = filtered_options.pass_angle
  AND dynamic_events.frame_start > filtered_options.frame_start
  AND dynamic_events.frame_start - filtered_options.frame_end <= 60
