config {
    type: "incremental",
    schema: "historical_data",
    name: "historical_phases_of_play",
    bigquery: {
        partitionBy: "season_name",
        clusterBy: ["match_id", "team_in_possession_id"]
    },
    assertions: {
        nonNull: ["match_id", "team_in_possession_id"]
    },
    tags: ["bi_weekly_incremental"]
}

SELECT
    pop.*,
    mm.season_name
FROM ${ref("skillcorner_external_data", "phases_of_play")} AS pop
JOIN ${ref("skillcorner_external_data", "match_metadata")} AS mm
    ON mm.match_id = pop.match_id
WHERE mm.season_name IN ('2021', '2021/2022', '2022', '2022/2023', '2023', '2023/2024', '2024', '2024/2025', '2025', '2025/2026', '2026')

${ when(incremental(), `AND mm.season_name IN ('2025/2026', '2026')`) }