config {
    type: "incremental",
    schema: "historical_data",
    name: "historical_match_metadata",
    bigquery: {
        clusterBy: ["match_id", "competition_edition_id", "home_team_id", "away_team_id"]
    },
    assertions:{
        nonNull: ["match_id", "competition_edition_id", "home_team_id", "away_team_id"]
    },
    tags: ["bi_weekly_incremental"]
}

pre_operations {
    ${when(incremental(), `DELETE FROM ${self()} WHERE ce.season_name IN ('2025/2026', '2026')`)}
}

SELECT mm.* 
FROM ${ref("skillcorner_external_data", "match_metadata")} AS mm
JOIN
    ${ref("skillcorner_external_data", "competition_editions")} AS ce
ON
    mm.competition_edition_id = ce.id
WHERE ce.season_name 
    IN ('2021', '2021/2022', '2022', '2022/2023', '2023', '2023/2024',  '2024/2025', '2025', '2024', '2025/2026', '2026')

${when(incremental(), `AND ce.season_name IN ('2025/2026', '2026')`)}