config {
    type: "incremental",
    schema: "historical_data",
    name: "historical_phases_of_play",
    bigquery: {
        clusterBy: ["match_id", "team_in_possession_id"]
    },
    assertions: {
        nonNull: ["match_id", "team_in_possession_id"]
    },
    tags: ["bi_weekly_incremental"]
}

pre_operations {
    ${when(incremental(), `DELETE FROM ${self()} WHERE season_name IN ('2025/2026', '2026')`)}
}

SELECT
    pop.*,
    ce.season_name
FROM ${ref("skillcorner_external_data", "phases_of_play")} AS pop
JOIN (
    SELECT match_id, competition_edition_id
    FROM ${ref("skillcorner_external_data", "match_metadata")}
    QUALIFY ROW_NUMBER() OVER (PARTITION BY match_id ORDER BY match_id) = 1
) AS mm
    ON mm.match_id = pop.match_id
JOIN ${ref("skillcorner_external_data", "competition_editions")} AS ce
    ON mm.competition_edition_id = ce.id
WHERE ce.season_name
    IN ('2021', '2021/2022', '2022', '2022/2023', '2023', '2023/2024', '2024', '2024/2025', '2025', '2025/2026', '2026')

${ when(incremental(), `AND ce.season_name IN ('2025/2026', '2026')`) }