config {
    type: "table",
    schema: "historical_data",
    name: "historical_phases_of_play",
    bigquery: {
        clusterBy: ["event_id", "event_type", "event_subtype"]
    },
    uniqueKey:["event_id"],
    assertions:{
        nonNull: ["event_id"]
    }
}

SELECT * FROM ${ref("skillcorner_external_data", "match_metadata")}
WHERE season_name 
    IN ('2021', '2021/2022', '2022', '2022/2023', '2023', '2023/2024',  '2024/2025', '2025', '2024', '2025/2026', '2026')