config {
    type: "incremental",
    schema: "historical_data",
    name: "historical_physical_data",
    bigquery: {
        clusterBy: ["player_id", "match_id", "competition_edition_id"]
    },
    assertions:{
        nonNull: ["player_id", "match_id"]
    },
    tags: ["bi_weekly_incremental"]
}

pre_operations {
    ${when(incremental(), `DELETE FROM ${self()} WHERE season_name IN ('2025/2026', '2026')`)}
}

SELECT
    * FROM ${ref("skillcorner_external_data", "physical_v3_data")}
    WHERE season_name 
    IN ('2021', '2021/2022', '2022', '2022/2023', '2023', '2023/2024',  '2024/2025', '2025', '2024', '2025/2026', '2026')

${when(incremental(), `AND season_name IN ('2025/2026', '2026')`)}