config {
    type: "table",
    schema: "analysis_team_sandbox",
    name: "playing_time_aggregates",
    description: "Player playing time",
    bigquery: {
        clusterBy: ["player_id", "team_id", "competition_edition_id"]
    },
    uniqueKey:["player_id", "team_id", "competition_edition_id", "competition_id", "season_id"],
    assertions:{
        uniqueKey: ["player_id", "team_id", "competition_edition_id", "competition_id", "season_id"],
        nonNull: ["player_id", "team_id", "competition_edition_id", "competition_id", "season_id"]
    }
}

SELECT 
  pp.player_id,
  pp.team_id,
  mm.competition_edition_id,
  ce.competition_id,
  ce.season_id,

  ANY_VALUE(pp.first_name) AS first_name,
  ANY_VALUE(pp.last_name) AS last_name,
  CONCAT(ANY_VALUE(pp.first_name), ' ', ANY_VALUE(last_name)) AS player_name,
  ANY_VALUE(pp.short_name) AS short_name,
  ANY_VALUE(pp.birthday) AS birthday,
  ANY_VALUE(pp.gender) AS gender,
  ANY_VALUE(ce.name) AS competition_edition_name,
  ANY_VALUE(ce.competition_name) AS competition_name,
  ANY_VALUE(ce.season_name) AS season_name,

  COUNT(*) as count_in_squad,

  SUM(
    CASE WHEN 
      pp.start_time = '00:00:00'
    THEN 1 ELSE 0 END
  )
  AS count_start_match,

  SUM(
    CASE WHEN 
      pp.start_time IS NOT NULL
      AND pp.start_time != '00:00:00'
    THEN 1 ELSE 0 END
  )
  AS count_sub_apperance,

  COUNT(*) * 90 as minutes_available,
  SUM(pp.minutes_played) AS minutes_played,
  (SUM(pp.minutes_played) / (COUNT(*) * 90)) * 100 as minutes_played_percentage

FROM
    ${ref("player_performances")} AS pp
JOIN
  ${ref("metadata", "match_metadata")} AS mm
ON
  pp.match_id = mm.match_id
JOIN
  ${ref("metadata", "competition_editions")} AS ce
ON
    mm.competition_edition_id = ce.id
GROUP BY
  pp.player_id, 
  pp.team_id, 
  mm.competition_edition_id, 
  ce.competition_id, 
  ce.season_id