config {
    type: "table",
    schema: "dynamic_events_sandbox",
    name: "phases_of_play",
    bigquery: {
        clusterBy: ["competition_edition_id", "team_in_possession_phase_type", "team_out_of_possession_phase_type"]
    },
    assertions:{
        nonNull: ["competition_edition_id", "team_in_possession_phase_type", "team_out_of_possession_phase_type"]
    }
}

WITH modified_phases AS (
  SELECT
    phases_of_play.*,    
    
    -- Additional match information.
    CAST(match_meta.competition_edition_id AS int64) AS competition_edition_id,
    ce.name AS competition_edition_name,
    ce.competition_id,
    ce.competition_name,
    ce.season_id,
    ce.season_name,
    CONCAT(match_meta.home_team_name, ' v ',match_meta.away_team_name,' (', match_meta.date_time, ')') AS match_name,

    CASE WHEN phases_of_play.team_in_possession_id = match_meta.home_team_id THEN match_meta.away_team_id ELSE match_meta.home_team_id END AS team_out_of_possession_id,
    CASE WHEN phases_of_play.team_in_possession_id = match_meta.home_team_id THEN match_meta.away_team_short_name ELSE match_meta.home_team_short_name END AS team_out_of_possession_shortname

    FROM     
      ${ref("events", "phases_of_play")} AS phases_of_play 
    JOIN 
      ${ref("metadata", "match_metadata")} AS match_meta  
    ON phases_of_play.match_id = match_meta.match_id
    JOIN 
      ${ref("metadata", "competition_editions")} AS ce  
    ON ce.id = match_meta.competition_edition_id
    WHERE
      ce.season_name IN ('2023/2024', '2024', '2024/2025', '2025', '2024', '2025/2026', '2026') or match_meta.competition_edition_id IN (168,198,360,235)
  )
SELECT * FROM modified_phases